# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.7

stages:
 - build
 - test

build:
 stage: build
 script:
   - python3 setup.py install
 tags:
  - 'docker'

test:
 stage: test
 script:
   - python3 setup.py install
   - cd tests
   - python3 -m unittest queryProjectTest.py
 tags:
  - "docker"



