name: Release and Publish to PyPi

# Only when PR are merged to MASTER
on:
  push:
    #types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env

      - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine pytest
          poetry install

      - name: Bump version push to Git, release to Github and Publish to PyPi
        run:
          semantic-release publish
        env:
          PYPI_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TWINE_REPOSITORY: api-saagie